name: app_vida_saludable
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  formz: ^0.6.0
  go_router: ^7.0.1
  intl: ^0.18.1
  mask_text_input_formatter: ^2.4.0
  material_design_icons_flutter: ^6.0.7096
  shared_preferences: ^2.1.1
  syncfusion_flutter_charts: ^21.2.8
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/icon/
    - assets/svg/
